apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
data:
  S3_REGION: ""
  S3_BUCKET: ""
  AWS_KEY: ""
  AWS_SECRET_KEY: ""

# [run.sh]
# echo "$AWS_KEY:$AWS_SECRET_KEY" > passwd && chmod 600 passwd
# s3fs "$S3_BUCKET" "$MNT_POINT" -o passwd_file=passwd  && tail -f /dev/null

# [ORCALE]
# s3fs BUCKET PATH \
#     -o url=https://[tenant-id].compat.objectstorage.[region-id].oraclecloud.com/ \
#     -o use_path_request_style \
#     -o nomultipart   